# Generated by Django 5.2.1 on 2025-11-05 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_producto_fotoprod_alter_tienda_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='FotoProd',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='Logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/'),
        ),
    ]
