# frontend/Dockerfile
FROM debian:stable-slim

# Instalar dependencias
RUN apt-get update && apt-get install -y curl unzip xz-utils git bash openssh-client

# Instalar Flutter
RUN git clone https://github.com/flutter/flutter.git /usr/local/flutter
ENV PATH="/usr/local/flutter/bin:/usr/local/flutter/bin/cache/dart-sdk/bin:${PATH}"

WORKDIR /app

COPY . .

RUN flutter config --enable-web
RUN flutter pub get
RUN flutter run -d 

target frontend: failed to solve: process "/bin/sh -c flutter build web --release" did not complete successfully: exit code: 1


# Servir el sitio web con un servidor HTTP
FROM nginx:stable-alpine
COPY --from=0 /app/build/web /usr/share/nginx/html

EXPOSE 80
